module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  agid_base: 0
  block: 0
  breakpoint: 0
  chosen: 0
  chosen_lib: 0
  ckeditor: 0
  config: 0
  config_devel: 0
  config_translation: 0
  content_translation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  entity_browser: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_entity: 0
  filter: 0
  geocoder: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  image: 0
  language: 0
  link: 0
  locale: 0
  maxlength: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  twig_field_value: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  sparkminimal: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  agid_back: 0
  italiagov: 0
  agid: 0
profile: sparkminimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: it
